run:
  deadline: 5m
  tests: false
  skip-dirs:
  - mermaidclient/internal
  - scyllaclient/internal
  silent: true

linters-settings:
  errcheck:
    check-blank: true
  lll:
    line-length: 180

linters:
  enable-all: true
  disable:
  - gas
  - interfacer
  - maligned
  - prealloc

issues:
  exclude-use-default: false
  exclude:
  - composite literal uses unkeyed fields
  - exported function New.+ should have comment or be unexported
  - Error return value of `.+\.Close` is not checked
  - Error return value of `net.SplitHostPort` is not checked
  - Error return value of `strconv.ParseBool` is not checked
