version: '3'

services:
#  scylla-manager:
#    image: scylladb/scylla-manager
#    networks:
#      public:
#        ipv4_address: 192.168.100.110
#    depends_on:
#      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla:${SCYLLA_VERSION}
    command: --smp 1 --api-address 0.0.0.0
    networks:
      public:
        ipv4_address: 192.168.100.100

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090
    network_mode: host
